name = "openlemma"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["botlib", "problems"]

[leanOptions]
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "botlib"

[[lean_lib]]
name = "problems"
